<?php

declare(strict_types=1);

namespace SuperAgent\CLI\Commands;

use SuperAgent\Config\ConfigLoader;
use SuperAgent\CLI\Terminal\Renderer;

/**
 * Initialize SuperAgent configuration.
 *
 * Creates the ~/.superagent/ directory and config.php file
 * with user-provided API keys and default settings.
 */
class InitCommand
{
    public function execute(array $options): int
    {
        $renderer = new Renderer();
        $renderer->banner();
        $renderer->info('Initializing SuperAgent configuration...');
        $renderer->newLine();

        $homeDir = ConfigLoader::homeDir();
        $configDir = $homeDir . '/.superagent';
        $configFile = $configDir . '/config.php';

        // Create config directory
        if (! is_dir($configDir)) {
            if (! @mkdir($configDir, 0755, true)) {
                $renderer->error("Failed to create config directory: {$configDir}");
                return 1;
            }
            $renderer->success("Created: {$configDir}");
        }

        // Create storage directory
        $storageDir = $configDir . '/storage';
        if (! is_dir($storageDir)) {
            @mkdir($storageDir, 0755, true);
        }

        // Check if config already exists
        if (file_exists($configFile)) {
            $renderer->warning("Config file already exists: {$configFile}");
            $overwrite = $renderer->confirm('Overwrite?');
            if (! $overwrite) {
                $renderer->info('Aborted.');
                return 0;
            }
        }

        // Collect configuration
        $config = [];

        // Provider selection
        $renderer->info('Select your default AI provider:');
        $renderer->line('  1) anthropic  (Claude — recommended)');
        $renderer->line('  2) openai     (GPT-4o)');
        $renderer->line('  3) ollama     (Local models)');
        $renderer->line('  4) openrouter (Multi-model)');
        $renderer->newLine();

        $choice = $renderer->ask('Provider [1]: ') ?: '1';
        $provider = match ($choice) {
            '2' => 'openai',
            '3' => 'ollama',
            '4' => 'openrouter',
            default => 'anthropic',
        };
        $config['default_provider'] = $provider;

        // API Key (skip for Ollama)
        if ($provider !== 'ollama') {
            $envVar = match ($provider) {
                'openai' => 'OPENAI_API_KEY',
                'openrouter' => 'OPENROUTER_API_KEY',
                default => 'ANTHROPIC_API_KEY',
            };

            $existingKey = getenv($envVar) ?: '';
            if ($existingKey) {
                $masked = substr($existingKey, 0, 8) . '...' . substr($existingKey, -4);
                $renderer->info("Found {$envVar} in environment: {$masked}");
                $useEnv = $renderer->confirm('Use this key?');
                if ($useEnv) {
                    $config['providers'][$provider]['api_key'] = $existingKey;
                }
            }

            if (empty($config['providers'][$provider]['api_key'])) {
                $key = $renderer->askSecret("Enter your {$envVar}: ");
                if (! empty($key)) {
                    $config['providers'][$provider]['api_key'] = $key;
                } else {
                    $renderer->warning("No API key provided. Set {$envVar} in your environment.");
                }
            }
        } else {
            // Ollama base URL
            $baseUrl = $renderer->ask('Ollama base URL [http://localhost:11434]: ') ?: 'http://localhost:11434';
            $config['providers']['ollama']['base_url'] = $baseUrl;
        }

        // Model
        $defaultModel = match ($provider) {
            'openai' => 'gpt-4o',
            'ollama' => 'llama3.1',
            'openrouter' => 'anthropic/claude-sonnet-4-6',
            default => 'claude-sonnet-4-6',
        };
        $model = $renderer->ask("Default model [{$defaultModel}]: ") ?: $defaultModel;
        $config['model'] = $model;

        // Write config file
        $configContent = "<?php\n\n/**\n * SuperAgent global configuration.\n * Generated by: superagent init\n * Date: " . date('Y-m-d H:i:s') . "\n */\n\nreturn " . $this->exportArray($config, 0) . ";\n";

        if (file_put_contents($configFile, $configContent) === false) {
            $renderer->error("Failed to write config file: {$configFile}");
            return 1;
        }

        // Set file permissions (not world-readable since it may contain API keys)
        @chmod($configFile, 0600);

        $renderer->newLine();
        $renderer->success("Configuration saved to: {$configFile}");
        $renderer->newLine();
        $renderer->info('You can now run:');
        $renderer->line('  superagent                    # Start interactive mode');
        $renderer->line('  superagent "your prompt"      # Run a one-shot task');
        $renderer->newLine();

        return 0;
    }

    /**
     * Export an array as formatted PHP code.
     */
    private function exportArray(array $array, int $indent): string
    {
        $pad = str_repeat('    ', $indent + 1);
        $closePad = str_repeat('    ', $indent);
        $lines = ["["];

        foreach ($array as $key => $value) {
            $keyStr = is_int($key) ? '' : "'" . addslashes((string) $key) . "' => ";

            if (is_array($value)) {
                $lines[] = "{$pad}{$keyStr}" . $this->exportArray($value, $indent + 1) . ",";
            } elseif (is_bool($value)) {
                $lines[] = "{$pad}{$keyStr}" . ($value ? 'true' : 'false') . ",";
            } elseif (is_null($value)) {
                $lines[] = "{$pad}{$keyStr}null,";
            } elseif (is_int($value) || is_float($value)) {
                $lines[] = "{$pad}{$keyStr}{$value},";
            } else {
                $lines[] = "{$pad}{$keyStr}'" . addslashes((string) $value) . "',";
            }
        }

        $lines[] = "{$closePad}]";

        return implode("\n", $lines);
    }
}
